example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path, include
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
# TODO: Implement Routings Here
from django.urls import path
from . import views

app_name = 'mywatchlist'

urlpatterns = [
     path('', views.show_mywatchlist_html, name='show_mywatchlist_html'),
    path('html/', views.show_mywatchlist_html, name='show_mywatchlist_html'),
    path('json/', views.show_watchlist_json, name='show_watchlist_json'),
    path('xml/', views.show_watchlist_xml, name='show_watchlist_xml'),


]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include
# TODO: Implement Routings Here

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
# TODO: Implement Routings Here
from django.urls import path
from . import views
app_name = 'todolist'

urlpatterns = [
    path('', views.show_todolist, name='show_todolist'),
    path('add/', views.add_todolist, name='add_todolist'),
    path('json/', views.show_json, name='show_json'),
    path('login/', views.login_user, name = 'login'),
    path('logout/', views.logout_user, name = 'logout'),
    path('register/', views.register, name='register'),
    path('create-task/', views.create_task, name='create_task'),




]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class WatchlistItem(models.Model):
    watched = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    rating = models.IntegerField(default=0)
    release_date = models.DateField(default = "0000-00-00")
    review = models.TextField(default = '')

todolist/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, models.CASCADE)
    date = models.DateField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField(default = "")
    

todolist/forms.py
from django import forms
from . import models

class CreateTaskForm(forms.ModelForm) :
    class Meta:
        model = models.Task
        fields = ['title', 'description']
        title = forms.CharField(max_length=255)
        description = forms.TextInput()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem
# TODO: Create your views here.
def show_katalog(request):
    data_katalog = CatalogItem.objects.all()
    context = {
    'list_katalog': data_katalog,
    'nama': 'Inaya Rahmanisa',
    'npm': '2106708330'
}
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import render
from mywatchlist.models import WatchlistItem

# Create your views here.
def show_mywatchlist_html(request):
    data_watchlist = WatchlistItem.objects.all()
    context = {
    'watch_list' : data_watchlist,
    'nama' : 'Inaya Rahmanisa',
    'npm'  : '2106708330',
    }
    return render(request, "mywatchlist.html", context)

def show_watchlist_json(request):       
    data = WatchlistItem.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_watchlist_xml(request):       
    data = WatchlistItem.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

todolist/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Task
from todolist.forms import CreateTaskForm
import datetime;

# Create your views here.

title_list = []
desc_list = []
@login_required(login_url='/todolist/login/')  
def show_todolist(request):
    context = {
    'nama' : 'Inaya Rahmanisa',
    'npm'  : '2106708330',
    'username' : request.user,
    }
    return render(request, "todolist.html", context)


def show_json(request):
    data = Task.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/todolist/login/')  
def add_todolist(request):
    if request.method == 'POST':
        title = request.POST.get("title")
        date = datetime.date.today()
        description = request.POST.get("description")

        new_barang = Task(title=title, date=date, description=description)
        new_barang.user = request.user
        new_barang.save()
        data = {'title':title, 'date':date, 'description':description}
        print(data)
        return JsonResponse(data, safe=False)

    return HttpResponseNotFound()

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse('todolist:show_todolist')) # membuat response
            response.set_cookie('username', username) #
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    return redirect('todolist:login')

@login_required(login_url='/todolist/login/')  
def create_task(request):
    form = CreateTaskForm()

    if request.method == 'POST':
        form = CreateTaskForm(request.POST)
        if form.is_valid():
            temp = form.save(commit=False)
            temp.user = request.user
            form.save()
            return redirect('/todolist/')
    context = {'form':form}
    return render(request, 'create_task.html', context)

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_katalog %}
    <tr>
        <th>{{barang.item_name}}</th>
        <th>{{barang.item_price}}</th>
        <th>{{barang.item_stock}}</th>
        <th>{{barang.rating}}</th>
        <th>{{barang.description}}</th>
        <th>{{barang.item_url}}</th>
    </tr>
{% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

{% block content %}
<h5>Nama: </h5>
<p>{{nama}}</p>
<h5>NPM: </h5>
<p>{{npm}}</p>
<table>
    <tr>
    <th>Watched</th>
    <th>Title</th>
    <th>Rating</th>
    <th>Release Date</th>
    <th>Review</th>

    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}{% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for movie in watch_list %}
        <tr>
            <th>{{movie.watched}}</th>
            <th>{{movie.title}}</th>
            <th>{{movie.rating}}</th>
            <th>{{movie.release_date}}</th>
            <th>{{movie.review}}</th>
        </tr>
    {% endfor %}

</table>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    {% block meta %}
    {% endblock meta %}
  </head>
  <body>
    {% block content %}
    <h1>Hello, world!</h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    {% endblock content %}
  </body>
</html>

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block content %}


<html>
    <head>
    <style>
        h2 {
            color: navy;
            justify-content: center;
            margin-top: 50px;
            text-align: center;
            margin-bottom: 70px;
        }
        body{
            background-color: rgb(125, 212, 183);
        }
        .tabel  {
            
            justify-content: center;
            text-align: center;
            margin-left: 200px;
            margin-right: 50px;
            margin-top: 50px;
        }
        .button {
            text-decoration: black;
            background-color: rgb(107, 132, 222);
            border: none;
            padding: 5px 10px;
            border-radius: 4px;
            font-weight: bold;
            text-align: center;
            transition-duration: 0.4s;
        
            }
        .button:hover {
        background-color: aliceblue;
            }
        .box    {
            margin: 0;
            position: absolute;
            top: 50%;
            left: 50%;
            -ms-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
            align-items: center;
            width: 900px;
            height: 700px;
            background-color: transparent;
            border-radius: 15px;
            box-shadow: 0 10px 10px 10px rgb(0, 0, 0, .2);
        }
        .link   {
            color: black;
            text-decoration: none;
        }
        @media only screen and (max-width: 600px) {
        body {
            background-color: white;
        }
        }


    </style>

    </head>

<body>
    <div class="box">
        <div class="tabel">
            <h2>Form Pembuatan Task</h2>
            <form method="POST" action="">
                {% csrf_token %}
                <table> 
                    {{form.as_table}}
                    <tr>  
                        <td></td>
                        <td><input type="submit" name="submit" value="Save" class = "button"/></td>  
                    </tr> 
                </table>
                <div class="tabel">
                    <button class="button"><a href="/todolist/" class="link" >Kembali</a></button>
                </div>
            </form>
            </table>   
        </div> 
    </div>
</body>
</html>


{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<html>
    <head>
    
    <style>
        
        body {
            background-color: cadetblue;
            background-image: url('{% static "flamingo.png" %}');
            background-position: center;
            background-position-y:top;
            background-repeat: no-repeat;
            background-size: cover;
        }
        h1  {
            justify-content: center;
            margin-top: 100px;
            text-align: center;
            margin-bottom: 20px;

        }
        .btn_login_btn {
            background-color: rgb(107, 132, 222);
            border: none;
            padding: 5px 10px;
            border-radius: 4px;
            font-weight: bold;
            text-align: center;
            transition-duration: 0.4s;
        
        }
        
        
        .btn_login_btn:hover {
            background-color: aliceblue;
        }
        .mb-3   {
            
            justify-content: center;
            text-align: center;
            margin-left: 50px;
            margin-right: 50px;
            margin-top: 50px;
        }
        .box    {
            margin: 0;
            position: absolute;
            top: 50%;
            left: 50%;
            -ms-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
            align-items: center;
            width: 500px;
            height: 500px;
            background-color: rgba(217, 217, 217, 0.30);
            border-radius: 15px;
            box-shadow: 0 10px 10px 10px rgb(0, 0, 0, .2);
        }
        @media only screen and (max-width: 600px) {
        body {
            background-color: white;
        }
        }
    </style>
    </head>

    <body>
    <div class = "login">

        <div class = "box">
        <form method="POST" action="">
            {% csrf_token %}
                <h1>Login</h1>
                <div class = "mb-3">
                    <label for="inputUsername" class="form-label" >Username</label>
                    <input type="text" name="username" placeholder="Username" class="form-control" id = "inputUsername">
                    <label for="inputPassword" class="form-label">Password</label>
                    <input type="password" name="password" placeholder="Password" class="form-control" id = "inputPassword">
                </div>

                <div class = "mb-3">
                <input class="btn_login_btn" type="submit" value="Login">
                </div>
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
        <div class = "mb-3">
        Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>
        </div>
        
        </div>
    </div>
    {% endblock content %}
    </body>
</html>

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  


<html>
    <head>
        <style>
            h1 {
                justify-content: center;
                margin-top: 10px;
                text-align: center;
                margin-bottom: 30px;
            }
            body   {
                background-color: rgb(156, 215, 217);
                background-position: center;
                background-repeat: no-repeat;
                background-size: cover;
            }
            .register    {
                text-align: center;
            }
            .box    {
            margin: 0;
            position: absolute;
            top: 50%;
            left: 50%;
            -ms-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
            align-items: center;
            width: 900px;
            height: 600px;
            background-color: transparent;
            border-radius: 15px;
            box-shadow: 0 10px 10px 10px rgb(0, 0, 0, .2);
            }
            .isi   {
                margin-top: 30px;
                margin-left: 50px;
                margin-right: 50px;
                padding: 70px 0;
                justify-content: center;
                text-align: center;
            }
            .tf {
            background-color: rgb(107, 132, 222);
            border: none;
            padding: 5px 10px;
            border-radius: 4px;
            font-weight: bold;
            text-align: center;
            transition-duration: 0.4s;
        
            }
            .tf:hover {
            background-color: aliceblue;
            }
            @media only screen and (max-width: 600px) {
            body {
                background-color: white;
            }
            }



        </style>
    </head>

    <body>
        <div class = "register">
            <div class="box">
                <div class = "isi">
                    <h1>Formulir Registrasi</h1>  
                        <form method="POST" >  
                            {% csrf_token %}  
                            <table>  
                                {{ form.as_table }}  
                                <tr>  
                                    <td></td>
                                    <td><input type="submit" name="submit" value="Daftar" class = "tf"/></td>  
                                </tr>  
                            </table>  
                        </form>

                    {% if messages %}  
                        <ul>   
                            {% for message in messages %}  
                                <li>{{ message }}</li>  
                                {% endfor %}  
                        </ul>   
                    {% endif %}
                </div>
            </div>
        </div>  
    </body>
</html>
{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

  <style>
    body    {
        background-color: rgb(228, 218, 254);
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }
    h2  {
        color: navy;
        justify-content: center;
        margin-top: 20px;
        text-align: center;
        margin-bottom: 50px;
    }
    .todolist   {
        text-align: center;
        
       
    }
    .button {
        text-decoration: black;
        background-color: rgb(107, 132, 222);
        border: none;
        padding: 5px 10px;
        border-radius: 4px;
        font-weight: bold;
        text-align: center;
        transition-duration: 0.4s;
        margin-bottom: 20px;
    
        }
    .button:hover {
        background-color: aliceblue;
        }
    .link   {
        color: black;
        text-decoration: none;
    }
    .mylayout   {
        
        justify-content: center;
        text-align: center;
        margin-left: 50px;
        margin-right: 50px;
        margin-top: 50px;
        margin-bottom: 100px;
    }
    
    @media only screen and (max-width: 600px) {
    body {
        background-color: white;
    }
    }

</style>
</head>
<body>
    <script>
        $(document).ready(function () {
        $.get('/todolist/json/', function (data) {
            data.map((todo) =>
            $('#table').append(
                `<tr" class="mylayout" >
                <div class="card">
                        <div class="card" style="background-color: rgb(59, 59, 135);">
                            <div class="card-body">
                            <h5 class="card-title" style="color: white">${todo.fields.title}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">${todo.fields.date}</h6>
                            <p class="card-text" style="color: white">${todo.fields.description}</p>
                        </div>
                </div>
            </tr>`
            )
            );
        });
        });
        $(document).ready(function () {
        $('#buttonajax').click(function (event) {
            const formData = {
            csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val(),
            title: $('#todo-title').val(),
            description: ($('#todo-desc').val()),
            };
            console.log(formData)
            $.ajax({
            type: 'POST',
            url: "/todolist/add/",
            data: formData,
            dataType: 'json',
            success: function(response) {
                $('#table').append(
                    `<tr" class="mylayout" >
                        <div class="card">
                                <div class="card" style="background-color: rgb(59, 59, 135)">
                                    <div class="card-body">
                                    <h5 class="card-title" style="color: white">${response.title}</h5>
                                    <h6 class="card-subtitle mb-2 text-muted">${response.date}</h6>
                                    <p class="card-text" style="color: white">${response.description}</p>
                                </div>
                        </div>
                </tr>`)
                    
                    
                        
            }

            }).done(function (data) {
            $('#message').text(data.message);
            $("#myModal").modal('hide');
            });

            event.preventDefault();
        });
        });
        
    </script>
  

  <div class = todolist>
    <h2>{{username}}'s Todolist</h2>
        <button class="button"><a href="{% url 'todolist:create_task' %}" class="link">Tambah Task Baru</a></button>
    <div class="container">
        <!-- Trigger the modal with a button -->
        <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Add Task</button>
    
        <!-- Modal -->
        <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
        
            <!-- Modal content-->
            <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Tambah Todo</h4>
            </div>
            <div class="modal-body">
                <form id="modalform" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="todo-title" class="col-form-label">Title</label>
                    <input type="text" class="form-control" id="todo-title">
                </div>
                <div class="mb-3">
                    <label for="todo-desc" class="col-form-label">Description:</label>
                    <input type="text" class="form-control" id="todo-desc" method="post">
                    
                </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <input type="submit" name="submit" value="Save" id="buttonajax">
            </div>
            </div>
            
        </div>
        </div>
        
    
    <table class="todolist" style="text-align: center ;align-items: center; justify-content: center;
    width: 900px;
    height: 600px; 
    margin-left: 100px;
    top: 50%;
    left: 50%;">
        <tr id="table" class= "mylayout">

        </tr>   
    </table>
        <button class="button"><a href="{% url 'todolist:logout' %}" class="link">Logout</a></button>
    </div>
</div>
  



</body>
</html>
{% endblock content %}